### ISSUE TITLE
queries for last updated

### ISSUE THREAD

**Issue by eroux** [buda-base/lds-queries#43]
- [ ] one query for all instance having an image instance that has been synced or updated since a certain date
- [ ] one query for all entities of type T (where type T is an argument) that have been created or updated since a certain date, probably with a limit (because for very big imports like NLM or FEMC that could drown everything else)
- [ ] one query counting all the entities of all types that have been created or updated since a certain date

perhaps the first and second should be merged and then the UI can sort the various types of updates...

**Comment by eroux** [comment]
(currently blocked by https://github.com/buda-base/lds-pdi/issues/198 for the most part)

**Comment by jimk-bdrc** [comment]
@eroux Archive-ops would run a query every day, during off-hours on the East Coast, To probably just count the image instances that have been updated since (today @ 00:00:00 EDT) - so the first query above (_one query for all instance having an image instance that has been synced or updated since a certain date_) would be the closest to AOs need to put this in the db.

**Comment by eroux** [comment]
perfect!
